# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A function to create an M matrix to help with
#' restricted cubic spline calculations
#'
#' @param precision how precise the calculation should be;
#' it will the be the number of rows in the output
#' @param k the number of knots used
#' @param dimensions the number of dimentions to create
#' (this grows the size VERY fast)
#' @param max the maximum value of the x values; default = 1
#' @param first_knot position of the first knot; default = 0.05 * max
#' @param last_knot position of the last knot; default = 0.95 * max
#' @return a matrix of size precision by k
#' @examples
#' make_matrix(1000, 5)
#' @export
make_matrix <- function(precision, k, dimensions = 1L, max = 1, first_knot = 0.05, last_knot = 0.95) {
    .Call(`_rcspline_make_matrix`, precision, k, dimensions, max, first_knot, last_knot)
}

#' A function that takes a vector and compatable matrix and
#' returns a restricted cubic spline
#'
#' @param vector A vector
#' @param matrix The M matrix to calculate the restricted cubic spline;
#' number of columns should be the same as the length of the vector
#' @return Vector with the spline values; length is the same as the number
#' of rows in matrix
#' @examples
#' M <- make_matrix(1000, 5)
#' spline_1d(v, M)
#' @export
spline_1d <- function(vector, matrix) {
    .Call(`_rcspline_spline_1d`, vector, matrix)
}

#' A function that takes a vector and compatable matrix and
#' returns a 2 dimensional restricted cubic spline
#'
#' @param vector A vector
#' @param matrix The M matrix to calculate the restricted cubic spline;
#' number of columns should be the same as the length of the vector
#' @return Vector with the sline values; length is the same as the number
#' of rows in matrix
#' @examples
#' M <- make_matrix(1000, 5, 2)
#' spline_2d(v, M)
#' @export
spline_2d <- function(vector, matrix) {
    .Call(`_rcspline_spline_2d`, vector, matrix)
}

